### ISSUE TITLE
Fix $PATH to use Julia 0.6.4

### ISSUE THREAD

**Issue by lagefreitas** [NaelsonDouglas/DistributedMachineLearningThesis#7]
@NaelsonDouglas, please use `sed` to fix the PATH to use Julia 0.6.4, i.e., `/opt/julia/bin`: 

```bash
cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/julia/bin"
 export PATH
```

**Comment by NaelsonDouglas** [comment]
Done [here](https://github.com/NaelsonDouglas/DistributedMachineLearningThesis/commit/68d7cb5b4c093f6856a2aaeb099343dca07fd5d4)

**Comment by lagefreitas** [comment]
it is not solved:

```bash
root@392b514fecb1:/# julia -v
julia version 0.4.7
```

**Comment by lagefreitas** [comment]
Julia 0.6.2 is set when creating the master container. For Workers, it uses Master's JULIA_HOME.
